### ISSUE TITLE
Crashes on Connection refused(offline server)

### ISSUE THREAD

**Issue by Zombs-R-Cute** [cemahseri/SteamQuery.NET#3]
Using the nuget 1.1.2 library, there is no exception for connection refused, and it crashes.

Unhandled Exception:
System.Net.Sockets.SocketException (0x80004005): Connection refused

**Comment by cemahseri** [comment]
Skill issue.

**Comment by Zombs-R-Cute** [comment]
Thank you so much for the explanation of how to catch the exception.

**Comment by cemahseri** [comment]
You're welcome.

Well, this is by design. I could handle the exception and return default information, which would not be useful. Perhaps another property can be added, such as `IsDataAvaliable` or `IsServerOnline` etc. But I think that there is no reason for that and letting the user handle the exception is a better approach.

So if your code looks like this;
```csharp
using var server = new GameServer("127.0.0.1:27015");

await server.PerformQueryAsync();
// or var information = await server.GetInformationAsync();
```

Wrap it with a try-catch block;
```csharp
using var server = new GameServer("127.0.0.1:27015");

try
{
    await server.PerformQueryAsync();
    // or var information = await server.GetInformationAsync();
}
catch (Exception exception)
{
    Console.WriteLine($"Oopsie woopsie! Fucky wucky: {exception}");
    // Return from method or call another method etc.
}
```

**Comment by Zombs-R-Cute** [comment]
Thank you.  Wasn't aware it could be caught like that, it's working now.

**Comment by cemahseri** [comment]
You're welcome. Keep up the good work!
